name: caddy-update

on:
  workflow_dispatch:
  schedule:
  - cron:  '00 12 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  caddy-update:
    name: update caddy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Run caddy-container-update
      run: |
        set -x

        # caddy_hash
        caddy_hash="$(
          git ls-remote https://github.com/porech/caddy-maxmind-geolocation master \
            | cut -f1 \
            | tail -1
        )"
        sed -i "s|^ENV CADDY_HASH.*$|ENV CADDY_HASH=$caddy_hash|" ./Dockerfile

        cat ./Dockerfile

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: caddy-update automated change
        signoff: true
        title: caddy container update
        body: Automated caddy container update
        labels: dependencies, 3. to review
        milestone: next
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: caddy-container-update
